---
title: "01_notas"
output: html_document
---

Material del curso:
https://lcolladotor.github.io/rnaseq_LCG-UNAM_2021/

Observaciones de algunos paquetes de bioconductor 
https://docs.google.com/spreadsheets/d/1FI6LG__AuRNYuPZNEMD-Bo0CpQmayd7ZqtjBF7uf_ts/edit#gid=0

Para crear un proyecto de R y ligarlo a GitHub 

1. Crear proyecto 
```{r}
# Crear el proyecto 
usethis::create_project("/path/my_new_project")

# Crear archivos .r 
usethis::use_r("name.R")
```

2. Obtener token y validar identidad 
```{r}
# Obtener token
usethis::create_github_token()

# Validar identidad 
gitcreds::gitcreds_set()

# En linux la validación expira, entonces puedes hacer esto para no volver a
# introducir el token 
usethis::edit_r_environ()

# Y agregas tu token → GITHUB_PAT= token
```

3. Inicializar repositorio Git y conectar con GitHub
```{r}
# Configurar Git. Agregar encabezado [user], name = nombre y email = correro.
usethis::edit_git_config()
# Inicializar repositorio de Git 
usethis::use_git()
# Conectamos con GitHub 
usethis::use_github()
```

Para crear tu perfil/página web

```{r}
# Crear Proyecto
usethis::create_project("lau-lhg.github.io")

# Inicializar Git y conectar a GitHub 
usethis::use_git()
usethis::use_github()

# Crear postcard y su template (onofre, jolla, jolla-blue, trestles)
postcards::create_postcard(template = "onofre")

# Commit, push y listo 
```

Biconductor y paquetes 

